# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

steps:
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: DockerRegistry
- task: Docker@2
  displayName: Build
  inputs:
    command: build
    Dockerfile: '**/Dockerfile'
    repository: 'kennygonsalves/server'
    tags: '$(Build.BuildId)'
- task: Docker@2
  displayName: Push
  inputs:
    command: push
    repository: kennygonsalves/server
    tags: '$(Build.BuildId)'
- task: CopyFiles@2
  displayName: Copy Files
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'gonsalveskenny.express-server-1'
    publishLocation: 'pipeline'
